# Generated by Django 3.1.7 on 2021-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_server', '0003_auto_20210227_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='tcp_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='udp_port',
            field=models.IntegerField(default=0),
        ),
    ]
