# Generated by Django 3.1.7 on 2021-02-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_server', '0004_auto_20210227_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerWorkerSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(0, 'Killed'), (1, 'Terminated'), (2, 'Running'), (3, 'Planned'), (4, 'Zombie')], max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_server.event')),
            ],
        ),
    ]
