# Generated by Django 3.1.7 on 2021-03-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_server', '0006_auto_20210312_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist_rules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.assistrules')),
                ('event_rules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.eventrules')),
                ('event_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.eventsettings')),
                ('server_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.serverconfig')),
                ('server_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.serversettings')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='assist_rules',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_rules',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_settings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='server_config',
        ),
        migrations.RemoveField(
            model_name='event',
            name='server_settings',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.AlterField(
            model_name='serverworkersettings',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_server.accevent'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
