# Generated by Django 3.1.7 on 2021-04-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_server', '0007_auto_20210327_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accevent',
            name='assist_rules',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.assistrules'),
        ),
        migrations.AlterField(
            model_name='accevent',
            name='event_rules',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.eventrules'),
        ),
        migrations.AlterField(
            model_name='accevent',
            name='event_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.eventsettings'),
        ),
        migrations.AlterField(
            model_name='accevent',
            name='server_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.serverconfig'),
        ),
        migrations.AlterField(
            model_name='accevent',
            name='server_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acc_server.serversettings'),
        ),
    ]
