# Generated by Django 3.1.7 on 2021-04-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_server', '0008_auto_20210405_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerWorkerSettings',
        ),
    ]
