# Generated by Django 3.1.7 on 2021-03-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20210328_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='car_class',
            field=models.CharField(choices=[('GT3', 'GT3'), ('GT4', 'GT4'), ('Multi', 'Multi')], default='Multi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='grid_type',
            field=models.CharField(choices=[('Main', 'Main'), ('Reversed', 'Reversed')], default='Main', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='mandatory_pit_stop_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='pilot_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='pilot_qualify',
            field=models.CharField(choices=[('AM', 'AM'), ('SILVER', 'SILVER'), ('PRO-AM', 'PRO-AM'), ('PRO', 'PRO')], default='AM', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='qualify_type',
            field=models.CharField(choices=[('Fastest', 'Fastest'), ('Average', 'Average')], default='Average', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/user-files/playlist-thumbs/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tyre_sets_count',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
