# Generated by Django 3.1.7 on 2021-04-02 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0003_auto_20210329_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbs'),
        ),
    ]
