# Generated by Django 3.1.7 on 2021-04-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20210402_1937'),
        ('playlists', '0004_auto_20210403_0022'),
    ]

    operations = [
    ]
