# Generated by Django 3.1.8 on 2021-05-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_merge_20210408_2340'),
        ('playlists', '0006_auto_20210509_1213'),
    ]

    operations = [
    ]
