# Generated by Django 3.1.8 on 2021-05-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_auto_20210521_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_ends_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_starts_at',
        ),
    ]
