# Generated by Django 3.1.7 on 2021-04-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('races', models.IntegerField(default=0)),
                ('bestlaps', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('img', models.ImageField(default='/static/images/Avatar.png', upload_to='avatars')),
                ('discord', models.CharField(default=0, max_length=20)),
                ('tag', models.CharField(default=0, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
