# Generated by Django 3.1.7 on 2021-04-02 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='country_flag',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=40)),
                ('track', models.CharField(default='0', max_length=20)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 4, 3, 0, 22, 8, 404735), null=True)),
                ('time', models.DateField(blank=True, default=datetime.datetime(2021, 4, 3, 0, 22, 8, 404735), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
