# Generated by Django 3.1.7 on 2021-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='country_flag',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
