# Generated by Django 3.1.8 on 2021-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_stats_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='steam_id',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
