# Generated by Django 3.1.7 on 2021-04-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20210403_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
