# Generated by Django 3.1.10 on 2021-05-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_stats_country_flag'),
        ('authorization', '0003_delete_event'),
    ]

    operations = [
    ]
