# Generated by Django 3.1.8 on 2021-05-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_stats_steam_id'),
        ('authorization', '0004_merge_20210506_1034'),
    ]

    operations = [
    ]
