# Generated by Django 3.2.3 on 2021-05-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_merge_20210521_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='Undefined', max_length=20)),
                ('country_flag', models.ImageField(default='/static/images/DefaultFlag.bmp', upload_to='flags')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='country',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='authorization.countries'),
        ),
    ]
