# Generated by Django 3.2.3 on 2021-05-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20210528_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='country',
        ),
        migrations.AddField(
            model_name='countries',
            name='stats',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='authorization.stats'),
        ),
    ]
