# Generated by Django 3.2.3 on 2021-05-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20210528_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
