# Generated by Django 3.2.3 on 2021-05-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_delete_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_flag', models.ImageField(default='/static/images/DefaultFlag.bmp', upload_to='flags')),
                ('country_name', models.CharField(default=0, max_length=25)),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.stats')),
            ],
        ),
    ]
