# Generated by Django 3.2.3 on 2021-05-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='stats',
        ),
        migrations.AddField(
            model_name='stats',
            name='country_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authorization.countries'),
            preserve_default=False,
        ),
    ]
