# Generated by Django 3.2.3 on 2021-05-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_auto_20210528_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='country_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authorization.countries'),
        ),
    ]
