# Generated by Django 3.2.3 on 2021-05-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_alter_stats_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='country_id',
            new_name='country',
        ),
    ]
