# Generated by Django 3.2.3 on 2021-05-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_rename_country_id_stats_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.countries'),
        ),
    ]
