# Generated by Django 3.2.3 on 2021-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_alter_countries_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='instagram',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='stats',
            name='twitch',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
