# Generated by Django 3.2.3 on 2021-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20210528_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='description',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
