# Generated by Django 3.2.3 on 2021-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0017_auto_20210529_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='description',
            field=models.TextField(default=0, max_length=500),
        ),
    ]
